spring:
  cloud:
    gateway:
      routes:
      - id: service-products
        uri: lb://service-products
        predicates:
        - Path=/api/products/**
        #- Header=token, \d+
        #- Header=Content-Type,application/json
        #- Method=GET, POST
        #- Query=color
        #- Cookie=color, blue
        filters:
        - StripPrefix=2
        # - ExampleCookie=Hi my message!, user ,StevenGuaman
        - name: ExampleCookie
          args:
            message: Hi, my message!
            cookieName: user
            cookieValue: StevenGuaman
      - id: service-items
        uri: lb://service-items
        predicates:
        - Path=/api/items/**
        filters:
        - StripPrefix=2
        - AddRequestHeader=token-request, 123456
        - SetResponseHeader=Content-Type, text/plain
        - AddRequestParameter=name, steven